### ISSUE TITLE
Ace.createEditSession method signature 

### ISSUE THREAD

**Issue by stockiNail** [Vertispan/gwt-ace#1]
The `Ace.createEditSession` method is defined as following:

```java
Document createEditSession(Ace.CreateEditSessionTextUnionType text, Object mode);
```
But the `mode` param is not simply an object but it's referring to the Mode object used for instance to syntax highlight  the code. The TextMode definition should be [here](https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/mode/text.js#L47) into ACE project.

In Closure extern file the method is defined as following:

```javascript
/**
 * Creates a new EditSession, and returns the associated Document.
 * @param {(!ace.Document|string)} text
 * @param {?} mode // TODO: define !ace.Mode.
 * @return {!ace.Document}
 */
ace.createEditSession = function(text, mode) {};
```
but in the ACE [source](https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/ace.js#L116), is following:

```javascript
/**
 * Creates a new [[EditSession]], and returns the associated [[Document]].
 * @param {Document | String} text {:textParam}
 * @param {TextMode} mode {:modeParam}
 * 
 **/
exports.createEditSession = function(text, mode) {
    var doc = new EditSession(text, mode);
    doc.setUndoManager(new UndoManager());
    return doc;
}
```

**Comment by niloc132** [comment]
The Mode type was a bit weird - I didn't find an obvious way to create the type declaration so that it made sense in JsInterop, but I didn't try for very long. As I understand it, it depends on how you are loading the various Modes that you are working with - if they are included via a `script` tag, or the `require()` call that ace can optionally provide, etc.

From the work you did before with Ace, how did you use modes: how did you include your text modes, etc?

**Comment by stockiNail** [comment]
@niloc132 in the prototype I did, the mode files were injected at runtime, when required. I included all js files into the project, I mapped them into a ClientBundle, create a singleton for every MODE and injected, when the mode will be requested.

The ACE `createEditSession `was as following:

```java
EditSession createEditSession(Document text, String mode);
```
because (as coded [here](https://github.com/ajaxorg/ace/blob/dbdf8aaad697e2ded8fd69249b72a7e898583afa/lib/ace/edit_session.js#L857-L865)) the `mode` param could be the OBJECT (but as you wrote, almost not possible to retrieve if if now I'm curious if there is a way) or the name of mode itself, as string.

**Comment by stockiNail** [comment]
@niloc132 `Ace.require` sounds the right way to have that mode object. Unfortunately that method is used to get other kind of modules (not only modes). I'm testing some implementations but not simple to find out a generic way to use it.

**Comment by niloc132** [comment]
For ease of use, it might make sense to provide some handmade java classes which abstract over that `require` method to provide the ability to download another mode at runtime.

We could also just use the String overload and remove the others as you suggest, and then ace will do the download for us? Or do you see an advantage to providing Mode instances, letting the developer interact directly with them?

**Comment by stockiNail** [comment]
For sure we can remove the usage of MODE as object, is usually not needed on normal usage.
The cons is that you can not develop any mode if needed, only in JavaScript instead of Java. Could be acceptable. But I would like to go on with some additional tests to understand better if anything is doable

**Comment by stockiNail** [comment]
From ACE doc:

> The mode can then be used like this:
> 
> ```javascript
>     var JavaScriptMode = ace.require("ace/mode/javascript").Mode;
>     editor.session.setMode(new JavaScriptMode());
> ```

Sounds difficult to me to be able to implement it by using only JsInterop.

**Comment by niloc132** [comment]
Okay, let's plan on that for the time being. I'm not entirely certain how that arequire().Mode works, but I'll take a look - it looks like it would need to do blocking IO, which isn't really ... a good idea.

We'll resolve this for now by providing the string only - I'll get CI fixed and then make this change. Will probably diff in a TODO also so that it is clear that we don't want to leave it this way.

**Comment by stockiNail** [comment]
Fully agree to go to string only!

**Comment by stockiNail** [comment]
Going to `string `implementtion, the `EditSession` constructors should be updated as well
